hod/urls.py
from django.urls import path
from .views import *

app_name = "hod"

urlpatterns = [
    path("teacher-profiles/", teachers_list, name="teachers_list"),
    path("teacher-requests/", teachers_request_list, name="teachers_request_list"),
    path("teacher-delete/<int:pk>/", teacher_delete, name="teacher_delete"),
    path(
        "teacher-request-accept/<int:pk>/",
        teacher_request_accept,
        name="teacher_request_accept",
    ),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users.views import redirect_on_login

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", redirect_on_login, name="redirect_on_login"),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "accounts/password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "accounts/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("accounts/", include("users.urls", namespace="users")),
    path("teachers/", include("teachers.urls", namespace="teachers")),
    path("hod/", include("hod.urls", namespace="hod")),
    path("students/", include("students.urls", namespace="students")),
    path("", include("core.urls")),
]

teachers/urls.py
from django.urls import path
from .views import *

app_name = "teachers"

urlpatterns = [
    path("student-profiles/", students_list, name="students_list"),
    path("student-requests/", students_request_list, name="students_request_list"),
    path("student-delete/<int:pk>/", student_delete, name="student_delete"),
    path(
        "student-request-accept/<int:pk>/",
        student_request_accept,
        name="student_request_accept",
    ),
    path("exams/<int:exam_pk>/results/", result_list, name="result_list"),
    path("results/<int:pk>/", result_detail, name="result_detail"),
]

teachers/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db import models

STANDARD_CHOICES = (
    ("FE", "FE"),
    ("SE", "SE"),
    ("TE", "TE"),
    ("BE", "BE"),
)

BRANCH_CHOICES = (
    ("CIVIL", "Civil Engineering"),
    ("COMP", "Computer Engineering"),
    ("EL", "Electrical Engineering"),
    ("ENTC", "Electronics and Telecommunication Engineering"),
    ("IT", "Information Technology"),
    ("ME", "Mechanical Engineering"),
    ("AI&DS", "Artificial Intelligence & Data Science"),
    ("AR", "Automation & Robotics"),
)

DIVISION_CHOICES = (
    ("A", "A"),
    ("B", "B"),
)


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_hod = models.BooleanField(default=False)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    standard = models.CharField(max_length=2, choices=STANDARD_CHOICES, default="FE")
    branch = models.CharField(max_length=5, choices=BRANCH_CHOICES, default="COMP")
    division = models.CharField(max_length=1, choices=DIVISION_CHOICES, default="A")
    roll_no = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("standard", "branch", "division", "roll_no")
        ordering = ("-created",)

    def __str__(self):
        return f"{self.standard} {self.branch} {self.division} {self.roll_no}"


class StudentRequest(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    standard = models.CharField(max_length=2, choices=STANDARD_CHOICES, default="FE")
    branch = models.CharField(max_length=5, choices=BRANCH_CHOICES, default="COMP")
    division = models.CharField(max_length=1, choices=DIVISION_CHOICES, default="A")
    roll_no = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"{self.standard} {self.branch} {self.division} {self.roll_no}"


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    standard = models.CharField(max_length=2, choices=STANDARD_CHOICES, default="FE")
    branch = models.CharField(max_length=5, choices=BRANCH_CHOICES, default="COMP")
    division = models.CharField(max_length=1, choices=DIVISION_CHOICES, default="A")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("standard", "branch", "division")
        ordering = ("-created",)

    def __str__(self):
        return f"{self.standard} {self.branch} {self.division}"


class TeacherRequest(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    standard = models.CharField(max_length=2, choices=STANDARD_CHOICES, default="FE")
    branch = models.CharField(max_length=5, choices=BRANCH_CHOICES, default="COMP")
    division = models.CharField(max_length=1, choices=DIVISION_CHOICES, default="A")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"{self.standard} {self.branch} {self.division}"

teachers/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from core.decorators import *
from core.models import Exam, Session
from users.models import Student, StudentRequest

User = get_user_model()


@login_required
@is_verified_teacher
def students_list(request):
    teacher = request.user.teacher
    search = request.GET.get("search", None)
    if search:
        students = User.objects.filter(
            student__standard=teacher.standard,
            student__branch=teacher.branch,
            student__division=teacher.division,
        ).filter(Q(username__icontains=search) | Q(email__icontains=search))
    else:
        students = User.objects.filter(
            student__standard=teacher.standard,
            student__branch=teacher.branch,
            student__division=teacher.division,
        )

    paginator = Paginator(students, 15)
    page = request.GET.get("page")
    try:
        students = paginator.page(page)
    except PageNotAnInteger:
        students = paginator.page(1)
    except EmptyPage:
        students = paginator.page(paginator.num_pages)

    return render(request, "teachers/students_list.html", {"students": students})


@require_POST
@login_required
@is_verified_teacher
def student_delete(request, pk):
    student = get_object_or_404(Student, pk=pk)
    teacher = request.user.teacher
    if (
        student.standard != teacher.standard
        or student.branch != teacher.branch
        or student.division != teacher.division
    ):
        raise PermissionDenied()

    student.delete()
    messages.success(request, "Profile deleted successfully")

    return redirect("teachers:students_list")


@login_required
@is_verified_teacher
def students_request_list(request):
    teacher = request.user.teacher
    search = request.GET.get("search", None)
    if search:
        students = User.objects.filter(
            studentrequest__standard=teacher.standard,
            studentrequest__branch=teacher.branch,
            studentrequest__division=teacher.division,
        ).filter(Q(username__icontains=search) | Q(email__icontains=search))
    else:
        students = User.objects.filter(
            studentrequest__standard=teacher.standard,
            studentrequest__branch=teacher.branch,
            studentrequest__division=teacher.division,
        )

    paginator = Paginator(students, 15)
    page = request.GET.get("page")
    try:
        students = paginator.page(page)
    except PageNotAnInteger:
        students = paginator.page(1)
    except EmptyPage:
        students = paginator.page(paginator.num_pages)

    return render(
        request, "teachers/students_request_list.html", {"students": students}
    )


@require_POST
@login_required
@is_verified_teacher
def student_request_accept(request, pk):
    studentrequest = get_object_or_404(StudentRequest, pk=pk)
    teacher = request.user.teacher
    if (
        studentrequest.standard != teacher.standard
        or studentrequest.branch != teacher.branch
        or studentrequest.division != teacher.division
    ):
        raise PermissionDenied()

    if Student.objects.filter(
        standard=studentrequest.standard,
        branch=studentrequest.branch,
        division=studentrequest.division,
        roll_no=studentrequest.roll_no,
    ).exists():
        messages.error(
            request,
            f"Profile with roll number {studentrequest.roll_no} already exists, please delete it first",
        )
    else:
        Student.objects.create(
            user=studentrequest.user,
            standard=studentrequest.standard,
            branch=studentrequest.branch,
            division=studentrequest.division,
            roll_no=studentrequest.roll_no,
        )
        studentrequest.delete()
        messages.success(request, "Profile request accepted")

    return redirect("teachers:students_request_list")


@login_required
@is_verified_teacher
def result_list(request, exam_pk):
    exam = get_object_or_404(Exam, pk=exam_pk)
    if exam.user != request.user:
        raise PermissionDenied()
    sessions = exam.session_set.filter(completed=True)

    paginator = Paginator(sessions, 15)
    page = request.GET.get("page")
    try:
        sessions = paginator.page(page)
    except PageNotAnInteger:
        sessions = paginator.page(1)
    except EmptyPage:
        sessions = paginator.page(paginator.num_pages)

    context = {
        "exam": exam,
        "sessions": sessions,
    }
    return render(request, "teachers/result_list.html", context)


@login_required
@is_verified_teacher
def result_detail(request, pk):
    session = get_object_or_404(Session, pk=pk, completed=True)
    if session.exam.user != request.user:
        raise PermissionDenied()

    search = request.GET.get("search", None)
    if search:
        answers = session.answer_set.filter(
            question__question__icontains=search
        ).order_by("question__created")
    else:
        answers = session.answer_set.all().order_by("question__created")

    paginator = Paginator(answers, 15)
    page = request.GET.get("page")
    try:
        answers = paginator.page(page)
    except PageNotAnInteger:
        answers = paginator.page(1)
    except EmptyPage:
        answers = paginator.page(paginator.num_pages)

    context = {"session": session, "answers": answers}
    return render(request, "teachers/result_detail.html", context)

teachers/templates/teachers/result_detail.html
{% extends "base.html" %}
{% load static %}
{% load my_extras %}
{% block content %}
    <h1 class="font-weight-bold">({{ session.exam.id }}) {{ session.exam }}</h1>
    <p>{{ session.student.standard }} {{ session.student.get_branch_display }} {{ session.student.division }} {{ session.student.roll_no }} | {{ session.submitted|date:"M d, Y" }}</p>
    <hr>
    <a href="{% url 'teachers:result_list' session.exam.pk %}" class="btn btn-secondary mb-1"><i class="fas fa-angle-left"></i> Back</a>

    <form>
    <div class="input-group my-3">
      <input class="form-control py-2" type="search" name="search" placeholder="Search...">
      <span class="input-group-append">
        <button class="btn btn-secondary">
            <i class="fa fa-search"></i>
        </button>
      </span>
    </div>
  </form>
  
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Question</th>
                    <th scope="col">Answer status</th>
                    <th scope="col">Marks obtain</th>
                    <th scope="col">Marks on correct answer</th>
                    <th scope="col">Marks on wrong answer</th>
                    <th scope="col">Student option</th>
                    <th scope="col">Correct option</th>
                </tr>
            </thead>
            <tbody id="search-table">
                {% for answer in answers %}
                    <tr>
                        <td>{{ answer.question }}</td>
                        <td>{{ answer.get_answer_status|bool_to_answer_status }}</td>
                        <td>{{ answer.get_marks }}</td>
                        <td>{{ answer.question.marks_on_correct_answer }}</td>
                        <td>{{ answer.question.marks_on_wrong_answer }}</td>
                        <td>{{ answer.answer }}) {{ answer.question|get_option_text:answer.answer }}</td>
                        <td>{{ answer.question.correct_answer }}) {{ answer.question|get_option_text:answer.question.correct_answer }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% include 'pagination.html' with page=answers %}

    <script type="text/javascript" src="{% static 'js/keep_params.js' %}"></script>
{% endblock content %}

teachers/templates/teachers/result_list.html
{% extends "base.html" %}
{% load static %}
{% load my_extras %}
{% block content %}
    <h1 class="font-weight-bold">Results</h1>
    <p>({{ exam.id }}) {{ exam }}</p>
    <hr>
    <a href="{% url 'exams_list' %}" class="btn btn-secondary px-3 mb-3"><i class="fas fa-angle-left"></i> Back</a>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Student standard</th>
                    <th scope="col">Student branch</th>
                    <th scope="col">Student division</th>
                    <th scope="col">Student roll number</th>
                    <th scope="col">Attempted questions</th>
                    <th scope="col">Total questions</th>
                    <th scope="col">Marks obtain</th>
                    <th scope="col">Max marks</th>
                    <th scope="col">Passing percentage</th>
                    <th scope="col">Passing status</th>
                    <th scope="col">Submitted on</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody id="search-table">
                {% for session in sessions %}
                    <tr>
                        <td>{{ session.student.standard }}</td>
                        <td>{{ session.student.get_branch_display }}</td>
                        <td>{{ session.student.division }}</td>
                        <td>{{ session.student.roll_no }}</td>
                        <td>{{ session.get_num_attempted_que }}</td>
                        <td>{{ session.get_num_total_que }}</td>
                        <td>{{ session.get_marks }}</td>
                        <td>{{ session.get_max_marks }}</td>
                        <td>{{ session.exam.passing_percentage }}%</td>
                        <td>{{ session.get_passing_status|bool_to_passing_status }}</td>
                        <td>{{ session.submitted|date:"M d, Y" }}</td>
                        <td><a href="{% url 'teachers:result_detail' session.pk %}" class="btn btn-sm btn-info"><i class="fas fa-eye"></i> View</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% include 'pagination.html' with page=sessions %}

{% endblock content %}

teachers/templates/teachers/students_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <h2 class="font-weight-bold">Students' profiles</h2>
    <p>{{ user.teacher.standard }} {{ user.teacher.get_branch_display }} {{ user.teacher.division }}</p>

    <form>
    <div class="input-group my-3">
      <input class="form-control py-2" type="search" name="search" placeholder="Search...">
      <span class="input-group-append">
        <button class="btn btn-secondary">
            <i class="fa fa-search"></i>
        </button>
      </span>
    </div>
  </form>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead class="thead-light">
                <tr>
                    <th scope="col">User ID</th>
                    <th scope="col">Username</th>
                    <th scope="col">Email</th>
                    <th scope="col">Roll number</th>
                    <th scope="col">Verified on</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody id="search-table">
                {% for student in students %}
                    <tr>
                        <td>{{ student.id }}</td>
                        <td>{{ student }}</td>
                        <td>{{ student.email }}</td>
                        <td>{{ student.student.roll_no }}</td>
                        <td>{{ student.student.created|date:"M d, Y" }}</td>
                        <td>
                            <form method="POST" action="{% url 'teachers:student_delete' student.student.pk %}">
                                {% csrf_token %}
                                <button class="btn btn-sm btn-danger px-3 mb-1"><i class="fas fa-trash-alt"></i> Delete</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% include 'pagination.html' with page=students %}

    <script type="text/javascript" src="{% static 'js/keep_params.js' %}"></script>
{% endblock content %}

teachers/templates/teachers/students_request_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    
    <h2 class="font-weight-bold">Students' profile requests</h2>
    <p>{{ user.teacher.standard }} {{ user.teacher.get_branch_display }} {{ user.teacher.division }}</p>

    <form>
    <div class="input-group my-3">
      <input class="form-control py-2" type="search" name="search" placeholder="Search...">
      <span class="input-group-append">
        <button class="btn btn-secondary">
            <i class="fa fa-search"></i>
        </button>
      </span>
    </div>
  </form>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead class="thead-light">
                <tr>
                    <th scope="col">User ID</th>
                    <th scope="col">Request ID</th>
                    <th scope="col">Username</th>
                    <th scope="col">Email</th>
                    <th scope="col">Roll number</th>
                    <th scope="col">Updated on</th>
                    <th scope="col">Created on</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody id="search-table">
                {% for student in students %}
                    <tr>
                        <td>{{ student.id }}</td>
                        <td>{{ student.studentrequest.id }}</td>
                        <td>{{ student }}</td>
                        <td>{{ student.email }}</td>
                        <td>{{ student.studentrequest.roll_no }}</td>
                        <td>{{ student.studentrequest.updated|date:"M d, Y" }}</td>
                        <td>{{ student.studentrequest.created|date:"M d, Y" }}</td>
                        <td>
                            <form method="POST" action="{% url 'teachers:student_request_accept' student.studentrequest.pk %}">
                                {% csrf_token %}
                                <button class="btn btn-sm btn-success px-3 mb-1"><i class="fas fa-check"></i> Accept</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% include 'pagination.html' with page=students %}

    <script type="text/javascript" src="{% static 'js/keep_params.js' %}"></script>
{% endblock content %}