hod/urls.py
from django.urls import path
from .views import *

app_name = "hod"

urlpatterns = [
    path("teacher-profiles/", teachers_list, name="teachers_list"),
    path("teacher-requests/", teachers_request_list, name="teachers_request_list"),
    path("teacher-delete/<int:pk>/", teacher_delete, name="teacher_delete"),
    path(
        "teacher-request-accept/<int:pk>/",
        teacher_request_accept,
        name="teacher_request_accept",
    ),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users.views import redirect_on_login

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", redirect_on_login, name="redirect_on_login"),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "accounts/password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "accounts/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("accounts/", include("users.urls", namespace="users")),
    path("teachers/", include("teachers.urls", namespace="teachers")),
    path("hod/", include("hod.urls", namespace="hod")),
    path("students/", include("students.urls", namespace="students")),
    path("", include("core.urls")),
]

users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path("register/", register, name="register"),
    path("profile/", profile, name="profile"),
    path("student-profile/", student_profile, name="student_profile"),
    path("student-delete/", student_delete, name="student_delete"),
    path("teacher-profile/", teacher_profile, name="teacher_profile"),
    path("teacher-delete/", teacher_delete, name="teacher_delete"),
    path("demo-login", demo_login, name="demo_login"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db import models

STANDARD_CHOICES = (
    ("FE", "FE"),
    ("SE", "SE"),
    ("TE", "TE"),
    ("BE", "BE"),
)

BRANCH_CHOICES = (
    ("CIVIL", "Civil Engineering"),
    ("COMP", "Computer Engineering"),
    ("EL", "Electrical Engineering"),
    ("ENTC", "Electronics and Telecommunication Engineering"),
    ("IT", "Information Technology"),
    ("ME", "Mechanical Engineering"),
    ("AI&DS", "Artificial Intelligence & Data Science"),
    ("AR", "Automation & Robotics"),
)

DIVISION_CHOICES = (
    ("A", "A"),
    ("B", "B"),
)


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_hod = models.BooleanField(default=False)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    standard = models.CharField(max_length=2, choices=STANDARD_CHOICES, default="FE")
    branch = models.CharField(max_length=5, choices=BRANCH_CHOICES, default="COMP")
    division = models.CharField(max_length=1, choices=DIVISION_CHOICES, default="A")
    roll_no = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("standard", "branch", "division", "roll_no")
        ordering = ("-created",)

    def __str__(self):
        return f"{self.standard} {self.branch} {self.division} {self.roll_no}"


class StudentRequest(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    standard = models.CharField(max_length=2, choices=STANDARD_CHOICES, default="FE")
    branch = models.CharField(max_length=5, choices=BRANCH_CHOICES, default="COMP")
    division = models.CharField(max_length=1, choices=DIVISION_CHOICES, default="A")
    roll_no = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"{self.standard} {self.branch} {self.division} {self.roll_no}"


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    standard = models.CharField(max_length=2, choices=STANDARD_CHOICES, default="FE")
    branch = models.CharField(max_length=5, choices=BRANCH_CHOICES, default="COMP")
    division = models.CharField(max_length=1, choices=DIVISION_CHOICES, default="A")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("standard", "branch", "division")
        ordering = ("-created",)

    def __str__(self):
        return f"{self.standard} {self.branch} {self.division}"


class TeacherRequest(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    standard = models.CharField(max_length=2, choices=STANDARD_CHOICES, default="FE")
    branch = models.CharField(max_length=5, choices=BRANCH_CHOICES, default="COMP")
    division = models.CharField(max_length=1, choices=DIVISION_CHOICES, default="A")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return f"{self.standard} {self.branch} {self.division}"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from core.models import Exam
from .models import *

ACCOUNT_TYPE_CHOICES = (
    ("S", "Student"),
    ("T", "Teacher"),
)


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    account_type = forms.ChoiceField(
        choices=ACCOUNT_TYPE_CHOICES, widget=forms.RadioSelect()
    )

    class Meta:
        model = User
        fields = ("account_type", "username", "email", "password1", "password2")


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "email")


class StudentForm(forms.ModelForm):
    standard = forms.CharField(disabled=True)
    branch = forms.CharField(disabled=True)
    division = forms.CharField(disabled=True)
    roll_no = forms.CharField(disabled=True)

    class Meta:
        model = Student
        exclude = ("user",)


class StudentRequestForm(forms.ModelForm):
    class Meta:
        model = StudentRequest
        exclude = ("user",)


class TeacherForm(forms.ModelForm):
    standard = forms.CharField(disabled=True)
    branch = forms.CharField(disabled=True)
    division = forms.CharField(disabled=True)

    class Meta:
        model = Teacher
        exclude = ("user",)


class TeacherRequestForm(forms.ModelForm):
    class Meta:
        model = TeacherRequest
        exclude = ("user",)

users/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import *
from .models import User


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            account_type = form.cleaned_data.get("account_type")
            if account_type == "S":
                user.is_student = True
            else:
                user.is_teacher = True
            user.save()

            messages.success(
                request, f"Account created for {user.username}. They can now login."
            )
            return redirect("login")
    else:
        form = UserRegisterForm()

    return render(request, "users/register.html", {"form": form})


@login_required
def profile(request):
    if request.method == "POST":
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()

            messages.success(request, "Profile updated successfully.")
            return redirect("users:profile")
    else:
        form = UserUpdateForm(instance=request.user)

    return render(request, "users/profile.html", {"form": form})


@login_required
def student_profile(request):
    user = request.user
    if hasattr(user, "student"):
        form = StudentForm(instance=user.student)

    elif request.method == "POST":
        if hasattr(user, "studentrequest"):
            form = StudentRequestForm(request.POST, instance=user.studentrequest)
        else:
            form = StudentRequestForm(request.POST)

        if form.is_valid():
            sr = form.save(commit=False)
            sr.user = user
            sr.save()

            messages.success(request, "Profile updated successfully.")
            return redirect("users:student_profile")
    else:
        if hasattr(user, "studentrequest"):
            form = StudentRequestForm(instance=user.studentrequest)
        else:
            form = StudentRequestForm()

    return render(request, "users/student_profile.html", {"form": form})


@require_POST
@login_required
def student_delete(request):
    student = request.user.student
    student.user = None
    student.save()
    messages.success(request, "Profile deleted successfully.")
    return redirect("users:student_profile")


@login_required
def teacher_profile(request):
    user = request.user
    if hasattr(user, "teacher"):
        form = TeacherForm(instance=user.teacher)

    elif request.method == "POST":
        if hasattr(user, "teacherrequest"):
            form = TeacherRequestForm(request.POST, instance=user.teacherrequest)
        else:
            form = TeacherRequestForm(request.POST)

        if form.is_valid():
            tr = form.save(commit=False)
            tr.user = user
            tr.save()

            messages.success(request, "Profile updated successfully.")
            return redirect("users:teacher_profile")
    else:
        if hasattr(user, "teacherrequest"):
            form = TeacherRequestForm(instance=user.teacherrequest)
        else:
            form = TeacherRequestForm()

    return render(request, "users/teacher_profile.html", {"form": form})


@require_POST
@login_required
def teacher_delete(request):
    request.user.teacher.delete()
    messages.success(request, "Profile deleted successfully.")
    return redirect("users:teacher_profile")


@login_required
def redirect_on_login(request):
    if request.user.is_student:
        if hasattr(request.user, "student"):
            return redirect("students:exams_list")
        else:
            return redirect("users:student_profile")

    elif request.user.is_teacher:
        if hasattr(request.user, "teacher"):
            return redirect("teachers:students_list")
        else:
            return redirect("users:teacher_profile")

    else:
        return redirect("hod:teachers_list")


@require_POST
def demo_login(request):
    user = User.objects.get(pk=1)
    login(request, user)
    return redirect("redirect_on_login")

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card mx-auto max-width-650">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4 pb-2">Login</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-success btn-block" type="submit"><i class="fas fa-sign-in-alt"></i> Sign In</button>
                    <small class="text-muted mt-1">
                        <a href="{% url 'password_reset' %}">Forgot Password?</a>
                    </small>
                </div>
            </form>
            <form method="POST" action="{% url 'users:demo_login' %}">
                {% csrf_token %}
                <button class="btn btn-block btn-dark">Demo login</button>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Need an account?
                    <a class="ml-2" href="{% url 'users:register' %}">Sign Up Now</a>
                </small>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "base.html" %}
{% block content %}
    <h2>You have been logged out!</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a><br>
        </small>
    </div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card mx-auto max-width-650">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4 pb-2">Reset Password</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-success btn-block" type="submit">Request Password Reset</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
    <div class="alert alert-info">
        Password has been set.
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a><br>
        </small>
    </div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card mx-auto max-width-650">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4 pb-2">Reset Password</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-success btn-block" type="submit">Reset Password</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password.
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card mx-auto max-width-650">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4 pb-2">Edit Profile</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-success btn-block" type="submit"><i class="fas fa-save"></i> Update</button>
                </div>
            </form>
        </div>
        <div class="card-footer">
            {% if user.is_student %}
                <a href="{% url 'users:student_profile' %}">Student Profile</a> | 
            {% endif %}
            {% if user.is_teacher %}
                <a href="{% url 'users:teacher_profile' %}">Teacher Profile</a> | 
            {% endif %}
            <a href="{% url 'password_reset' %}">Reset Password</a>
        </div>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="card mx-auto max-width-650">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4 pb-2">Register</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-success btn-block" type="submit"><i class="fas fa-sign-in-alt"></i> Sign Up</button>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already have an account?
                    <a class="ml-2" href="{% url 'login' %}">Sign In</a>
                </small>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/student_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if user.student %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            Your account is verified
        </div>
    {% else %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            Your account is unverified. Create a profile and wait until your teacher accepts it
        </div>
    {% endif %}

    <div class="card mx-auto max-width-650">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4 pb-2">Edit Student Profile</legend>
                    {% if user.studentrequest %}
                        <p>Request ID: {{ user.studentrequest.id }}</p>
                    {% endif %}

                    {{ form|crispy }}
                </fieldset>

                {% if not user.student %}
                    <div class="form-group">
                        <button class="btn btn-success btn-block" type="submit">
                            {% if user.studentrequest %}<i class="fas fa-save"></i> Update{% else %}<i class="fas fa-plus"></i> Create{% endif %}
                        </button>
                    </div>
                {% endif %}
            </form>

            {% if user.student %}
                <form method="POST" action="{% url 'users:student_delete' %}">
                    {% csrf_token %}
                    <button class="btn btn-danger btn-block"><i class="fas fa-trash-alt"></i> Delete</button>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock content %}

users/templates/users/teacher_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if user.teacher %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
            Your account is verified
        </div>
    {% else %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            Your account is unverified. Create a profile and wait until an HOD accepts it
        </div>
    {% endif %}

    <div class="card mx-auto max-width-650">
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4 pb-2">Edit Teacher Profile</legend>
                    {% if user.teacherrequest %}
                        <p>Request ID: {{ user.teacherrequest.id }}</p>
                    {% endif %}

                    {{ form|crispy }}
                </fieldset>

                {% if not user.teacher %}
                    <div class="form-group">
                        <button class="btn btn-success btn-block" type="submit">
                            {% if user.teacherrequest %}<i class="fas fa-save"></i> Update{% else %}<i class="fas fa-plus"></i> Create{% endif %}
                        </button>
                    </div>
                {% endif %}
            </form>

            {% if user.teacher %}
                <form method="POST" action="{% url 'users:teacher_delete' %}">
                    {% csrf_token %}
                    <button class="btn btn-danger btn-block"><i class="fas fa-trash-alt"></i> Delete</button>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock content %}