core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("teachers/exams/", exams_list, name="exams_list"),
    path("teachers/exams/create/", exam_create, name="exam_create"),
    path("teachers/exams/<int:pk>/", exam_detail, name="exam_detail"),
    path("teachers/exams/<int:pk>/edit/", exam_edit, name="exam_edit"),
    path("teachers/exams/<int:pk>/delete/", exam_delete, name="exam_delete"),
    path(
        "teachers/exams/<int:exam_pk>/question-create/",
        question_create,
        name="question_create",
    ),
    path(
        "teachers/questions/<int:pk>/edit/",
        question_edit,
        name="question_edit",
    ),
    path(
        "teachers/questions/<int:pk>/delete/",
        question_delete,
        name="question_delete",
    ),
    path("students/exams/<int:exam_pk>/", exam_start, name="exam_start"),
    path(
        "students/exams/<int:exam_pk>/submit/",
        exam_submit,
        name="exam_submit",
    ),
    path(
        "students/exams/<int:exam_pk>/clear/",
        answer_clear,
        name="answer_clear",
    ),
    path(
        "students/exams/<int:exam_pk>/answer/",
        answer_submit,
        name="answer_submit",
    ),
    path(
        "students/exams/<int:exam_pk>/question-list/",
        question_list,
        name="question_list",
    ),
    path("students/exams/<int:exam_pk>/bookmark/", bookmark, name="bookmark"),
]

hod/urls.py
from django.urls import path
from .views import *

app_name = "hod"

urlpatterns = [
    path("teacher-profiles/", teachers_list, name="teachers_list"),
    path("teacher-requests/", teachers_request_list, name="teachers_request_list"),
    path("teacher-delete/<int:pk>/", teacher_delete, name="teacher_delete"),
    path(
        "teacher-request-accept/<int:pk>/",
        teacher_request_accept,
        name="teacher_request_accept",
    ),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users.views import redirect_on_login

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", redirect_on_login, name="redirect_on_login"),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "accounts/password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "accounts/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("accounts/", include("users.urls", namespace="users")),
    path("teachers/", include("teachers.urls", namespace="teachers")),
    path("hod/", include("hod.urls", namespace="hod")),
    path("students/", include("students.urls", namespace="students")),
    path("", include("core.urls")),
]

students/urls.py
from django.urls import path
from .views import *

app_name = "students"

urlpatterns = [
    path("exams/", exams_list, name="exams_list"),
    path("exams/<int:pk>/start/", exam_start, name="exam_start"),
    path("results/", result_list, name="result_list"),
    path("results/<int:pk>/", result_detail, name="result_detail"),
]

teachers/urls.py
from django.urls import path
from .views import *

app_name = "teachers"

urlpatterns = [
    path("student-profiles/", students_list, name="students_list"),
    path("student-requests/", students_request_list, name="students_request_list"),
    path("student-delete/<int:pk>/", student_delete, name="student_delete"),
    path(
        "student-request-accept/<int:pk>/",
        student_request_accept,
        name="student_request_accept",
    ),
    path("exams/<int:exam_pk>/results/", result_list, name="result_list"),
    path("results/<int:pk>/", result_detail, name="result_detail"),
]

users/urls.py
from django.urls import path
from .views import *

app_name = "users"

urlpatterns = [
    path("register/", register, name="register"),
    path("profile/", profile, name="profile"),
    path("student-profile/", student_profile, name="student_profile"),
    path("student-delete/", student_delete, name="student_delete"),
    path("teacher-profile/", teacher_profile, name="teacher_profile"),
    path("teacher-delete/", teacher_delete, name="teacher_delete"),
    path("demo-login", demo_login, name="demo_login"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
         <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script type="text/javascript">
            var jQuery_3_6_0 = $.noConflict(true);
        </script>

        <title>{% block title%}Online Examination System{% endblock title%}</title>
        {% block head %}{% endblock head %}
    </head>
    <body>
        {% block navbar %}{% include "navbar.html" %}{% endblock navbar %}

        <div class="container pb-4">
        {% if messages%}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif%}

        {% block content %}{% endblock content %}
        </div>

        {% block footer %}{% endblock footer %}

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/navbar.html
{% load my_extras %}
<nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top mb-4">
    <div class="container">
        <!-- Brand -->
        <a class="navbar-brand font-weight-bold" href="#">Online Examination System</a>

        <!-- Toggler Button -->
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbar-links">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar Links -->
        <div class="collapse navbar-collapse" id="navbar-links">
            <ul class="navbar-nav  ml-auto">
                {% if user.is_authenticated %}
                    {% if user.is_student %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'students:exams_list' %}">Active exams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'students:result_list' %}">Results</a>
                        </li>
                    {% endif %}
                    {% if user.is_teacher %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'exams_list' %}">Your exams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'teachers:students_list' %}">Students' profiles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'teachers:students_request_list' %}">Students' profile requests</a>
                        </li>
                    {% endif %}
                    {% if user.is_hod %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'hod:teachers_list' %}">Teachers' profiles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'hod:teachers_request_list' %}">Teachers' profile requests</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<!--Pagination-->
<nav class="d-flex justify-content-center wow fadeIn">
  <ul class="pagination pg-blue">

    <!--Arrow left-->
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link js-keep-params" href="?page={{ page.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% endif %}

    {% for num in page.paginator.page_range %}
      {% if page.number == num %}
        <li class="page-item active">
          <a class="page-link js-keep-params" href="?page={{ num }}">{{ num }}
            <span class="sr-only">(current)</span>
          </a>
        </li>
      {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
        <li class="page-item">
          <a class="page-link js-keep-params" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if page.has_next %}
      <li class="page-item">
        <a class="page-link js-keep-params" href="?page={{ page.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
<!--Pagination-->